name: Python Application CI

on:
  push:
    branches:
      - main
      - develop  # Add any other branches as needed
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures the entire git history is available if needed

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Configure Poetry
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: poetry install

    - name: Source environment variables from env.sh
      run: source env.sh
      shell: bash

    - name: Run tests using Make
      run: poetry run make test
      shell: bash
